### ISSUE TITLE
Crashes when joining servers?

### ISSUE THREAD

**Issue by ghost** [radmanplays/MeteorX-ts#9]
This is probably something I am doing wrong, sorry if this is the wrong place for this. Whenever I join a server, it crashes, and the error log says it was because of a ticking entity. I have tried several servers, not gonna say which because they are not anarchy. I have the latest version of the client, and eagler reborn beta 1.2, which was pre-compiled from the eagler archive github page. I am on a different device,  so I can't copy the full crash log, but it says 
`java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading 'amount') 
at TypeError: Cannot read properties of null (reading 'amount')
at BIC (file:// (full file path) /Eaglerreborn_beta1.2_1.8_offline_international.html:10890:143`

And then repeats more file locations. Sorry I can't put the full log

**Comment by radmanplays** [comment]
fixed

**Comment by leahanderson1** [comment]
this is fixed in the prerelease build of eagler reborn, have radman send it to you.

**Comment by radmanplays** [comment]
fixed
